apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-test
  labels:
    app: microservice-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-test
  template:
    metadata:
      labels:
        app: microservice-test
    spec:
      containers:
      - name: microservice-test
        image: <your-dockerhub-username>/microservice-test:latest
        ports:
        - containerPort: 4444
        env:
        - name: NODE_ENV
          value: "production"
