apiVersion: v1
kind: Service
metadata:
  name: microservice-test-service
  labels:
    app: microservice-test
spec:
  type: NodePort
  ports:
  - port: 4444
    targetPort: 4444
    nodePort: 44441
  selector:
    app: microservice-test
